[project]
name = "maintenance"
dynamic = [ "version" ]
authors = [
    { name = "Katulos", email = "123748719+Katulos@users.noreply.github.com" }
]
maintainers = [
    { name = "Katulos", email = "123748719+Katulos@users.noreply.github.com"}
]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: Implementation :: PyPy",
]
requires-python = ">= 3.10"
dependencies = [
    "adaptix>=3.0.0b11",
    "aiogram>=3.21.0",
    "aiogram-dialog>=2.4.0",
    "aiojobs>=1.4.0",
    "asyncclick>=8.1.8",
    "dishka>=1.6.0",
    "fastapi>=0.116.1",
    "fluent-runtime>=0.4.0",
    "odoorpc>=0.10.1",
    "orjson>=3.11.1",
    "pyyaml>=6.0.2",
    "redis>=6.2.0",
    "uvicorn>=0.35.0",
]

[tool.setuptools.dynamic]
version = {attr = "app.__version__"}

[project.scripts]
mnt = "app.cli.commands:cli"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
app= ['locales/*']

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
