services:
  bot:
    env_file:
      - .env
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - WORKSPACE=${WORKSPACE}
    command: sleep infinity
    ports:
      - "8000:8000"
    networks:
      - default
    volumes:
      - ..:${WORKSPACE}:cached
    depends_on:
      - db
      - local-bot-api
      - redis

  db:
    env_file:
      - .env
    image: postgres:15-alpine
    volumes:
      - db:/var/lib/postgresql/data:z
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - default
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.50"
    #       memory: 512M
    #     reservations:
    #       cpus: "0.25"
    #       memory: 256M

  local-bot-api:
    # image: aiogram/telegram-bot-api:latest
    image: ghcr.io/lukaszraczylo/tdlib-telegram-bot-api-docker/telegram-api-server:latest
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"
    networks:
      - default
    command: >
      --local
      --dir /var/lib/telegram-bot-api
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.50"
    #       memory: 512M
    #     reservations:
    #       cpus: "0.25"
    #       memory: 256M

  redis:
    env_file:
      - .env
    image: redis:8-alpine
    ports:
      - "${REDIS_PORT}:5432"
    networks:
      - default
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.50"
    #       memory: 512M
    #     reservations:
    #       cpus: "0.25"
    #       memory: 256M

volumes:
  telegram-bot-api-data:
  db:

networks:
  default:
