"""Initial.

Revision ID: 607612a75041
Revises:
Create Date: 2025-09-08 16:29:28.119837

"""

import typing as t

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "607612a75041"
down_revision: str | None = None
branch_labels: str | t.Sequence[str] | None = None
depends_on: str | t.Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "maintenance_equipment_category",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("odoo_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk__maintenance_equipment_category"),
        ),
        sa.UniqueConstraint(
            "odoo_id",
            name=op.f("uq__maintenance_equipment_category__odoo_id"),
        ),
    )
    op.create_table(
        "maintenance_stage",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("odoo_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__maintenance_stage")),
        sa.UniqueConstraint(
            "odoo_id",
            name=op.f("uq__maintenance_stage__odoo_id"),
        ),
    )
    op.create_table(
        "res_users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("odoo_id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "employee_type",
            sa.Enum(
                "EMPLOYEE",
                "STUDENT",
                "TRAINEE",
                "CONTRACTOR",
                "FREELANCE",
                name="employeetype",
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__res_users")),
        sa.UniqueConstraint("odoo_id", name=op.f("uq__res_users__odoo_id")),
    )
    op.create_table(
        "maintenance_equipment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("odoo_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("serial_no", sa.String(), nullable=True),
        sa.Column("maintenance_count", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("technician_user_id", sa.Integer(), nullable=True),
        sa.Column("owner_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["maintenance_equipment_category.id"],
            name=op.f(
                "fk__maintenance_equipment__category_id__maintenance_equipment_category",
            ),
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["res_users.id"],
            name=op.f("fk__maintenance_equipment__owner_user_id__res_users"),
        ),
        sa.ForeignKeyConstraint(
            ["technician_user_id"],
            ["res_users.id"],
            name=op.f(
                "fk__maintenance_equipment__technician_user_id__res_users",
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__maintenance_equipment")),
        sa.UniqueConstraint(
            "odoo_id",
            name=op.f("uq__maintenance_equipment__odoo_id"),
        ),
    )
    op.create_table(
        "maintenance_request",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("odoo_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("stage_id", sa.Integer(), nullable=False),
        sa.Column("equipment_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "kanban_state",
            sa.Enum("NORMAL", "BLOCKED", "DONE", name="kanbanstate"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["maintenance_equipment.id"],
            name=op.f(
                "fk__maintenance_request__equipment_id__maintenance_equipment",
            ),
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["maintenance_stage.id"],
            name=op.f("fk__maintenance_request__stage_id__maintenance_stage"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["res_users.id"],
            name=op.f("fk__maintenance_request__user_id__res_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__maintenance_request")),
        sa.UniqueConstraint(
            "odoo_id",
            name=op.f("uq__maintenance_request__odoo_id"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("maintenance_request")
    op.drop_table("maintenance_equipment")
    op.drop_table("res_users")
    op.drop_table("maintenance_stage")
    op.drop_table("maintenance_equipment_category")
    op.execute("DROP TYPE IF EXISTS kanbanstate CASCADE")
    op.execute("DROP TYPE IF EXISTS employeetype CASCADE")
    # ### end Alembic commands ###
